name:                glossat
version:             0.3.0.0
github:              "shnarazk/glossat"
license:             BSD3
author:              "S. Narazki"
maintainer:          "narazaki@nagasaki-u.ac.jp"
copyright:           "2018 Shuji Narazaki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shnarazk/glossat#readme>

default-extensions:   Strict

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.10
  - ghc-prim >= 0.5
  - primitive >= 0.6
  - random
  - vector >= 0.12
  - gloss

library:
  ghc-options:
    - -fwarn-missing-signatures
    - -funbox-strict-fields
  source-dirs: src

executables:
  glossat-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
    - -fwarn-missing-signatures
    - -funbox-strict-fields
#    - -O2
    dependencies:
    - glossat

tests:
  glossat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - glossat
